module.exports = {
  // ...existing code...
  presets: [
    // ...existing presets...
    '@babel/preset-react',
  ],
  plugins: [
    // ...existing plugins...
    '@babel/plugin-syntax-jsx',
  ],
  // ...existing code...
};
